Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/peter/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/peter/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/peter/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/peter/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/peter/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
display_quiz("examples/questions.json", 
             colors={
               '--jq-many-choice-bg': '#224dea',
               '--jq-multiple-choice-bg': '#a45995'
             }
            )
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [43mdisplay_quiz[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mexamples/questions.json[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      2[0m [43m             [49m[43mcolors[49m[38;5;241;43m=[39;49m[43m{[49m
[1;32m      3[0m [43m               [49m[38;5;124;43m'[39;49m[38;5;124;43m--jq-many-choice-bg[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m#224dea[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      4[0m [43m               [49m[38;5;124;43m'[39;49m[38;5;124;43m--jq-multiple-choice-bg[39;49m[38;5;124;43m'[39;49m[43m:[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m#a45995[39;49m[38;5;124;43m'[39;49m
[1;32m      5[0m [43m             [49m[43m}[49m
[1;32m      6[0m [43m            [49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/jupyterquiz/dynamic.py:176[0m, in [0;36mdisplay_quiz[0;34m(ref, num, shuffle_questions, shuffle_answers, preserve_responses, border_radius, question_alignment, max_width, colors)[0m
[1;32m    173[0m [38;5;28;01melse[39;00m:
[1;32m    174[0m     [38;5;66;03m#print("File detected")[39;00m
[1;32m    175[0m     script [38;5;241m+[39m[38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mvar questions[39m[38;5;132;01m{[39;00mdiv_id[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;124m"[39m
[0;32m--> 176[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mref[49m[43m)[49m [38;5;28;01mas[39;00m file:
[1;32m    177[0m         [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m file:
[1;32m    178[0m             script [38;5;241m+[39m[38;5;241m=[39m line

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'examples/questions.json'

